services:
  puppeteer:
    name: "MCP Puppeteer Server"
    description: "Puppeteer MCP server for browser automation (Docker container)"
    triggeredBy:
      - manual
    commands:
      start: |
        # Force cleanup of any existing Puppeteer containers
        echo "Cleaning up any existing Puppeteer containers..."
        docker rm -f puppeteer 2>/dev/null || true
        sleep 2  # Give Docker time to clean up

        echo "Starting Puppeteer MCP server with Docker..."
        docker run -i --rm --init -e DOCKER_CONTAINER=true --name puppeteer mcp/puppeteer

      ready: |
        if docker ps | grep -q puppeteer; then
          echo "Puppeteer MCP server is running"
          exit 0
        else
          echo "Puppeteer MCP server is not running"
          exit 1
        fi

      stop: |
        echo "Stopping Puppeteer MCP server container..."
        docker stop puppeteer || true
        echo "Removing Puppeteer MCP server container..."
        docker rm -f puppeteer || true